package GUI;


import BL.LCantidadProd;
import BL.LInventarioProduct;
import BL.LReservacion;
import Clases.Productos;
import Clases.ReservacionVO;
import Modelo.vo.vo.PreciosVO;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexa
 */
public class GUI_RevisarReservaciones extends javax.swing.JFrame {


    /**
     * Creates new form GUI_RevisarReservaciones
     */
    public GUI_RevisarReservaciones() throws ClassNotFoundException, SQLException, IOException {
        initComponents();
        cargarTitulos();
        ConsultarReservacion();
        mostrarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        saldoacumulado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitulo.setFont(new java.awt.Font("Broadway", 1, 28)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setText("Sus articulos reservados ");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(table1);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("Confirmar Reservación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("Subtotal");

        saldoacumulado.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setText("USD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(txtTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(645, 645, 645)
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(saldoacumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(622, 622, 622)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(saldoacumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel modelo;
    LInventarioProduct manejadorBL = new LInventarioProduct();
    LCantidadProd manejador2 = new LCantidadProd();
    int rsn_id;
    LReservacion manejadorBL3 = new LReservacion();

    public void cargarTitulos() {
        modelo = new DefaultTableModel() {
            @Override //Redefinimos el método getColumnClass
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                        return Icon.class;
                    case 1:
                        return Object.class;
                    case 2:
                        return Object.class;
                    case 3:
                        return Object.class;
                    case 4:
                        return Object.class;
                    case 5:
                        return Object.class;
                    case 6:
                        return Object.class;

                    default:
                        return Object.class;
                }
            }
        };

        //Se setea el modelo a la tabla
        table1.setModel(modelo);
        //Se da nombres a las columnas
        modelo.addColumn("Imagen Articulo");
        modelo.addColumn("Codigo Articulo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Total");

    }

    public void ConsultarReservacion() throws ClassNotFoundException, SQLException {
        ArrayList<ReservacionVO> lista = manejadorBL3.consultarId_AIngresar();
        for (ReservacionVO actual : lista) {
            rsn_id = actual.getRes_id();
        }
    }

    Object[] modeloTemp = new Object[6];
    double saldoTotal;
    String[] codigo;
    double[] saldo;
    int[] cantidadS;

    public void mostrarProductos() throws ClassNotFoundException, SQLException, IOException {
        ArrayList<Productos> lista = manejadorBL.ConsultarProductsReservados(rsn_id);
        ArrayList<PreciosVO> lista2 = manejador2.ConsultarPreciosPSeleccionados(rsn_id);
        codigo = new String[lista.size()];
        saldo = new double[lista2.size()];
        cantidadS = new int[lista2.size()];
        int i = 0, j = 0;
        for (PreciosVO actual2 : lista2) {

            cantidadS[i] = actual2.getRsv_cantidad();
            saldo[i] = actual2.getSaldo();
            saldoTotal += actual2.getSaldo();
            i++;
        }
        for (Productos actual : lista) {

            String code = String.valueOf(actual.getP_Codigo());
            codigo[j] = code;
            String nomb = String.valueOf(actual.getP_nombre());
            String precio = String.valueOf(actual.getP_precio());
            InputStream foto = actual.getP_imge();
            BufferedImage bf = ImageIO.read(foto);

            ImageIcon img = new ImageIcon(bf);

            ImageIcon icono = new ImageIcon(img.getImage().getScaledInstance(110, 70, Image.SCALE_SMOOTH));

            modeloTemp[0] = icono;
            modeloTemp[1] = code;
            modeloTemp[2] = nomb;
            modeloTemp[3] = precio;
            modeloTemp[4] = cantidadS[j];
            modeloTemp[5] = saldo[j];
            j++;
            table1.setRowHeight(70);
            modelo.addRow(modeloTemp);

        }
        String Subtotal = String.format("%.2f", saldoTotal);
        saldoacumulado.setText(Subtotal);
        System.out.println(codigo[0]);
    }
    
    

    public void ActualizarCantidadesProducts() throws SQLException, FileNotFoundException, ClassNotFoundException, IOException {
        int resultado = 0;
        //Inicializacion de variables

        for (int i = 0; i < cantidadS.length; i++) {

            int cantidad = cantidadS[i];
            String cod = codigo[i];
            //Envia la nueva informacion
            Productos prod = new Productos(cod, cantidad);

            resultado = manejadorBL.ActualizarProductos(prod);
        }
        if (resultado == 1) {
            JOptionPane.showMessageDialog(null, "MUCHAS GRACIAS POR SU RESERVA");
        } else {
            JOptionPane.showMessageDialog(null, "NO SE PUDO REGISTRAR");
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ActualizarCantidadesProducts();
        } catch (SQLException | FileNotFoundException | ClassNotFoundException ex) {
            Logger.getLogger(GUI_RevisarReservaciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GUI_RevisarReservaciones.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_RevisarReservaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_RevisarReservaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_RevisarReservaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_RevisarReservaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI_RevisarReservaciones().setVisible(true);

                } catch (ClassNotFoundException | SQLException | IOException ex) {
                    Logger.getLogger(GUI_RevisarReservaciones.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel saldoacumulado;
    private javax.swing.JTable table1;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables

}
