package GUI;

import BL.LCantidadProd;
import BL.LInventarioProduct;
import BL.LReservacion;
import BL.LUsuarios;
import Clases.Productos;
import Clases.ReservacionVO;
import Clases.Usuario;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author alexa
 */
public final class ReservacionProductos extends javax.swing.JFrame {


    /**
     * Creates new form ReservacionProductos
     */
    public ReservacionProductos() throws ClassNotFoundException, SQLException, IOException {
        initComponents();
        cargarComboProductos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboProductos = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        combo_Disponible = new javax.swing.JComboBox<>();
        txtsubtitle = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtStock = new javax.swing.JLabel();
        txtprecio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextPane();
        sale = new javax.swing.JTextField();
        avanzar = new javax.swing.JButton();
        moneda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(23, 22, 22));

        txtTitulo.setFont(new java.awt.Font("Broadway", 1, 28)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setText("Bienvenido ");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reservación de Productos");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Productos");

        comboProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductosActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(49, 134, 49));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtsubtitle.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtsubtitle.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Forte", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(170, 12, 12));
        jLabel5.setText("-->");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Qty:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio:");

        txtStock.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtprecio.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtprecio.setForeground(new java.awt.Color(255, 255, 255));
        txtprecio.setText("         0");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Detalles:");

        txtDetalles.setEditable(false);
        txtDetalles.setBackground(new java.awt.Color(23, 22, 22));
        txtDetalles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDetalles.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtDetalles.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txtDetalles);

        sale.setBackground(new java.awt.Color(23, 22, 22));

        avanzar.setText("jButton2");
        avanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanzarActionPerformed(evt);
            }
        });

        moneda.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        moneda.setForeground(new java.awt.Color(255, 255, 255));
        moneda.setText(" $");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(sale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(36, 36, 36)
                                        .addComponent(moneda, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtsubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(txtTitulo)))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(8, 8, 8)
                                        .addComponent(combo_Disponible, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(avanzar)
                                .addGap(14, 14, 14))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(comboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sale, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(comboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtsubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(txtprecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel6))
                                    .addComponent(combo_Disponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(avanzar)
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Declaraciones
    LInventarioProduct manejadorBL = new LInventarioProduct();
    LUsuarios manejadorBL2 = new LUsuarios();   
    LReservacion manejadorBL3 = new LReservacion();
    LCantidadProd manejador4 = new LCantidadProd();    
    boolean repetir = false;
    
    public void cargarComboProductos() throws ClassNotFoundException, SQLException, IOException {
        ArrayList<Productos> lstAdmin = new ArrayList<>();
        lstAdmin = manejadorBL.ConsultarProducts();
        comboProductos.insertItemAt("Seleccione...", 0);
        comboProductos.setSelectedIndex(0);
        for (Productos admin : lstAdmin) {
            //Usuario obtAdmin = new Usuario(admin.getUs_id(), admin.getUs_nombres());
            comboProductos.addItem(admin.getP_nombre());
        }
    }

    public void cargarDisponiblidad() throws ClassNotFoundException, SQLException, IOException {
        ArrayList<Productos> lstAdmin = new ArrayList<>();
        
        String nombre = comboProductos.getSelectedItem().toString();
        lstAdmin = manejadorBL.ConsultProductsPorNm(nombre);
        for (Productos admin : lstAdmin) {
            p_id = admin.getP_id();
            txtsubtitle.setText(admin.getP_nombre());
            combo_Disponible.removeAllItems();
            for (int i = 0; i < admin.getCantidad(); i++) {
                String num = String.valueOf(i);
                combo_Disponible.addItem(num);
            }
            txtprecio.setText(String.valueOf(admin.getP_precio()));
            if (admin.getCantidad() > 0) {
                txtStock.setText(admin.getP_disponibilidad());
                txtStock.setForeground(Color.GREEN);
            } else {
                txtStock.setText(admin.getP_disponibilidad());
                txtStock.setForeground(Color.RED);
            }

            txtDetalles.setText(admin.getP_descripcion());

            InputStream foto = admin.getP_imge();
            BufferedImage bf = ImageIO.read(foto);

            ImageIcon img = new ImageIcon(bf);

            ImageIcon icono = new ImageIcon(img.getImage().getScaledInstance(180, 200, Image.SCALE_SMOOTH));

            imagen.setIcon(icono);
        }
    }
    
    //Inserta el numero de resevacion
    public void insertarReservacion() throws SQLException {
        int resultado;
        //Inicializacion de variables
        int user = id_us;
        //Envia la nueva informacion   
        resultado = manejadorBL3.Insertar_Reservacion(user);
        if (resultado == 1) {
            JOptionPane.showMessageDialog(null, "DATOS REGISTRADOS");
        } else {
            JOptionPane.showMessageDialog(null, "NO SE PUDO REGISTRAR");
        }
    }   
    
    //Inserta la cantidad de la reservacion
    public void insertarPrecios() throws SQLException{
        int resultado;
        //Inicializacion de variables
        double precio = Double.parseDouble(txtprecio.getText());
        int cantidad = Integer.parseInt(combo_Disponible.getSelectedItem().toString());
        
        int reserv = rsn_id;
        int prod = p_id;
        //Envia la nueva informacion   
        resultado = manejador4.Insertar_Reservacion(precio, cantidad, reserv, prod);
        if (resultado == 1) {
            JOptionPane.showMessageDialog(null, "DATOS REGISTRADOS");
        } else {
            JOptionPane.showMessageDialog(null, "NO SE PUDO REGISTRAR");
        }   
    }
    
    int id_us;
    int p_id;
    int rsn_id;
    //Consulta el id del usuario con el que ingreso
    public void ConsultarUsuarios() throws ClassNotFoundException, SQLException {
        ArrayList<Usuario> lista = manejadorBL2.consultarIUsuario(sale.getText());

        for (Usuario actual : lista) {
            id_us = actual.getID();
        }
    }
    
    //Consulta el ide de la reservacion que se hara en ese momento
    public void ConsultarReservacion() throws ClassNotFoundException, SQLException {
        ArrayList<ReservacionVO> lista = manejadorBL3.consultarId_AIngresar();
        for (ReservacionVO actual : lista) {
            rsn_id = actual.getRes_id();
        }
    }
       
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ConsultarUsuarios();
            
            if(repetir == false){
               insertarReservacion(); 
               ConsultarReservacion();
               insertarPrecios();
            }else{
                ConsultarReservacion();
               insertarPrecios();           
            }
                  
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ReservacionProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        repetir = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductosActionPerformed
        try {
            cargarDisponiblidad();
        } catch (ClassNotFoundException | SQLException | IOException ex) {
            Logger.getLogger(ReservacionProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboProductosActionPerformed

    private void avanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanzarActionPerformed
        this.dispose();
        GUI_RevisarReservaciones f;
        try {
            f = new GUI_RevisarReservaciones();
            f.setVisible(true);
        } catch (ClassNotFoundException | SQLException | IOException ex) {
            Logger.getLogger(ReservacionProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("La siguiente seccion esta en desarrollo");
        
       
        
    }//GEN-LAST:event_avanzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservacionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservacionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservacionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservacionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ReservacionProductos().setVisible(true);
                } catch (ClassNotFoundException | SQLException | IOException ex) {
                    Logger.getLogger(ReservacionProductos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avanzar;
    private javax.swing.JComboBox<String> comboProductos;
    private javax.swing.JComboBox<String> combo_Disponible;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel moneda;
    public static javax.swing.JTextField sale;
    private javax.swing.JTextPane txtDetalles;
    private javax.swing.JLabel txtStock;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JLabel txtprecio;
    private javax.swing.JLabel txtsubtitle;
    // End of variables declaration//GEN-END:variables

}
